---
- hosts: "all"
  remote_user: root
  tasks:
   - name: Install packages.
     yum:
       name: ['yum-utils','device-mapper-persistent-data','lvm2','epel-release']
   - name: Configure the docker-ce repo.
     get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
     become: yes
   - name: Install docker-ce.
     yum:
      name: ['docker-ce','epel-release','python-pip']
   - name: adding existing user 'root' to group docker
     user:
      name: 'root'
      groups: docker
      append: yes
   - name: enable docker service
     systemd:
      name: docker
      enabled: yes
      masked: no
   - name: Make sure docker service is running
     systemd:
      state: started
      name: docker
   - name: install docker-py
     pip:
      name: docker-py
