---
- hosts: "all"
  remote_user: root
  tasks:
   - name: Pull and run SeaWeed master container.
     docker_container:
      name: seaweed_master
      image: chrislusf/seaweedfs
      restart_policy: always
      entrypoint: /entrypoint.sh master -ip={{ ansible_host }} -port=9334
      state: started
      ports:
       - "9334:9334"
       - "19334:19334"
      volumes:
       - /opt/weedfs/data:/data
   - name: Wait for MySQL to start
     wait_for:
      port: 9334
      delay: 5
   - name: Pull and run SeaWeed volume container.
     docker_container:
      name: seaweed_volume
      image: chrislusf/seaweedfs
      restart_policy: always
      entrypoint: /entrypoint.sh volume -dir="/data" -port=8800 -port.public=8800 -publicUrl={{ ansible_host }}:8800 -mserver={{ ansible_host }}:9334
      state: started
      ports:
       - "8800:8800"
       - "18800:18800"
      volumes:
       - /opt/weedfs/data:/data
  #  - name: Restart SolR service
  #    docker_container:
  #     name: seaweed_volume
  #     restart: yes
   - name: Creates an entry to reboot seaweed volume on restart
     cron:
      name: "a job for reboot seaweed master"
      special_time: reboot
      job: "docker restart seaweed_master"
