---
- hosts: all
  remote_user: root
  tasks:
   - name: Pull and run MySql container.
     docker_container:
      name: mysql
      image: mysql:5.6.20
      state: started
      command:
      volumes:
       - /opt/mysql:/etc/mysql
      env:
       MYSQL_ROOT_PASSWORD="mysql!@#$"
      ports:
       - "3306:3306"
   - name: Wait for MySQL to start
     wait_for:
      port: 3306
      delay: 5
